
package com.epam.lab3.ws;

import com.epam.lab3.models.Category;
import com.epam.lab3.models.News;
import com.epam.lab3.models.ObjectFactory;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NewspaperService", targetNamespace = "http://ws.lab3.epam.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NewspaperService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.epam.lab3.models.News
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNews", targetNamespace = "http://ws.lab3.epam.com/", className = "com.epam.lab3.models.AddNews")
    @ResponseWrapper(localName = "addNewsResponse", targetNamespace = "http://ws.lab3.epam.com/", className = "com.epam.lab3.models.AddNewsResponse")
    public News addNews(
        @WebParam(name = "arg0", targetNamespace = "")
        News arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.epam.lab3.models.News
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNews", targetNamespace = "http://ws.lab3.epam.com/", className = "com.epam.lab3.models.GetNews")
    @ResponseWrapper(localName = "getNewsResponse", targetNamespace = "http://ws.lab3.epam.com/", className = "com.epam.lab3.models.GetNewsResponse")
    public News getNews(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.epam.lab3.models.Category>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCategories", targetNamespace = "http://ws.lab3.epam.com/", className = "com.epam.lab3.models.GetAllCategories")
    @ResponseWrapper(localName = "getAllCategoriesResponse", targetNamespace = "http://ws.lab3.epam.com/", className = "com.epam.lab3.models.GetAllCategoriesResponse")
    public List<Category> getAllCategories();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.epam.lab3.models.News>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllNewsByCategory", targetNamespace = "http://ws.lab3.epam.com/", className = "com.epam.lab3.models.GetAllNewsByCategory")
    @ResponseWrapper(localName = "getAllNewsByCategoryResponse", targetNamespace = "http://ws.lab3.epam.com/", className = "com.epam.lab3.models.GetAllNewsByCategoryResponse")
    public List<News> getAllNewsByCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateNews", targetNamespace = "http://ws.lab3.epam.com/", className = "com.epam.lab3.models.UpdateNews")
    @ResponseWrapper(localName = "updateNewsResponse", targetNamespace = "http://ws.lab3.epam.com/", className = "com.epam.lab3.models.UpdateNewsResponse")
    public boolean updateNews(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
